### ISSUE TITLE
Side pages options and info [Relay]

### ISSUE THREAD

**Issue by kevkevinpal** [stakwork/sphinx-swarm#10]
After this is finished we can start to add the proper info to the pages
https://github.com/stakwork/sphinx-swarm/issues/9

lets start with relay's info
for now it might make sense to put whatever is in the config as info to display

for now just create a function that getsRelay info which takes in an identifier that will be the name of service
ex
```
getRelayInfo("relay1.sphinx")

//we can mock the response below
returns(
{
    isSetup: boolean //can use /is_setup endpoint
    IP: String,
    port: Number,
    connectionString?: String,
    and I'm sure we'll find more
}
)

------------
Alias
------------
Is_setup: false
IP:port
We might need a delete button somewhere on this page too

**Comment by kevkevinpal** [comment]
maybe instead of `is_setup` we can have a `Status`

**Comment by kevkevinpal** [comment]
Display connection string as a QR code too

**Comment by kevkevinpal** [comment]
Restart or shut down button would be nice

**Comment by Evanfeenstra** [comment]
Definitely restart/shutdown buttons for every service will be cool. I guess each side page will have some things in common, and some unique things per service

The QR connection info will be different if its a multitenant relay (with proxy). We'll need a "users" section that also shows the balances and connection QR per user (tobi will work on the relay side for that https://github.com/stakwork/sphinx-relay/issues/463)
