### ISSUE TITLE
CLN <-> boltwall

### ISSUE THREAD

**Issue by Evanfeenstra** [stakwork/sphinx-swarm#113]
We need boltwall to use CLN instead of LND

The CLN credentials (ca cert, client cert, and client key) are are accessible to boltwall. 

https://github.com/stakwork/sphinx-swarm/blob/master/src/images/boltwall.rs

**Comment by tobi-bams** [comment]
@Evanfeenstra here is the config for CLN support

CLN_TLS_LOCATION="/Users/oluwatobibamidele/Desktop/work/sphinx/sphinx-stack/cln/cln2/regtest/ca.pem"
CLN_TLS_KEY_LOCATION="/Users/oluwatobibamidele/Desktop/work/sphinx/sphinx-stack/cln/cln2/regtest/client-key.pem"
CLN_TLS_CHAIN_LOCATION="/Users/oluwatobibamidele/Desktop/work/sphinx/sphinx-stack/cln/cln2/regtest/client.pem"
CLN_URI="localhost:10020"

**Comment by kevkevinpal** [comment]
worth linking this here

https://github.com/stakwork/jarvis-boltwall/pull/47
