### ISSUE TITLE
Mobile signer

### ISSUE THREAD

**Issue by Evanfeenstra** [stakwork/sphinx-swarm#129]
In the "connect hardware" screen, you should have an option to choose "hardware" or "phone signer"

Scan the QR from the Sphinx Stack 
<img width="290" alt="Screen Shot 2023-08-22 at 11 33 50 AM" src="https://github.com/stakwork/sphinx-swarm/assets/7184040/ad19918f-b5b9-459e-844c-55b0ece01894">

You will get the `mqtt` url and the `network`, which you can use to start the MQTT signer

keep the mnemonic the same all the time

After first time setting up the signer, then you should try to re-connect any time that the app opens

**Comment by tomastiminskas** [comment]
@Evanfeenstra port will be always 1883? Or it will be included in the QR as part of the url?
