### ISSUE TITLE
SuperAdmin

### ISSUE THREAD

**Issue by Evanfeenstra** [stakwork/sphinx-swarm#142]
Super Admin site to view all swarms, and run actions on them

V1:
- list of active swarms
- description that can be updated by the admin
- healthcheck
- Size of each instance
- Map to Tribe/Tribes its tied to

V2:
- upgrade an image
- map credentials? like pointing a second brain to a different lightning node?
- create a new swarm?
- delete a swarm?

**Comment by Evanfeenstra** [comment]
Feature: list the # of tribes that a swarm is hooked up to. 

Frontend can query tribes server like this: GET  `/tribes/app_urls/swarm8,swarm9,swarm10` and will get back a list of tribes per swarm. Then each row in the table should show like "1 tribe", "3 tribes" etc.

If you hover or click that cell in the table, it should pop up a menu that shows the tribe names. Also you can click each one and open (in a new tab) the tribes page with the name of the tribe, like `https://tribes.sphinx.chat/t/planetsphinx`

@tobi-bams

**Comment by tomsmith8** [comment]
@Evanfeenstra We now have a couple newer swarms. How can we easily get these added to 'superadmin' dash?

**Comment by tomsmith8** [comment]
https://app.superadmin.sphinx.chat/ Currently showing all swarms that have dynamic address as down when they are not. We need to change the call to use correct domain?

**Comment by Evanfeenstra** [comment]
fixed it
