### ISSUE TITLE
Require password change on first login

### ISSUE THREAD

**Issue by tomsmith8** [stakwork/sphinx-swarm#146]
**Task**

When logging into a new swarm for the first time, we should require that the user change their password.

This should avoid all swarms having the same default username & password.

### Design
When a new user logs in, they are presented with this screen.
<img width="1249" alt="Screenshot 2023-11-22 at 2 50 26 PM" src="https://github.com/stakwork/sphinx-swarm/assets/32662508/5c83c688-11a3-43e3-9a38-8af9bb7f3636">

If they are given a specific set of user credentials, they will be prompted with the next screen. Note that the default text inside the "username" box is different:
<img width="1204" alt="Screenshot 2023-11-22 at 3 01 43 PM" src="https://github.com/stakwork/sphinx-swarm/assets/32662508/558ff6e4-1e80-4af6-9d4d-04de0a79cbb7">

Frontend should also validate the email format before accepting. If it is a valid email address, the log-in will turn blue and the credentials should be saved. Once log-in is clicked, the username and pw will be saved in our backend. You can use [this endpoint](https://github.com/stakwork/sphinx-swarm/blob/53b44ec0da825c82ada8b68a9fa3c6039dd6e728/app/src/auth/ChangePassword.svelte#L4) to update the password. Use [this endpoint](https://github.com/stakwork/sphinx-swarm/blob/master/src/routes.rs#L187) to update the username.
<img width="1211" alt="Screenshot 2023-11-22 at 2 59 04 PM" src="https://github.com/stakwork/sphinx-swarm/assets/32662508/6d2271e7-1a07-43d1-9cd2-1d41ef022e8c">

If a user submits an incorrectly formatted email address, wipe out the information and use a red text to specify the following: `Please submit a valid email address`.

<img width="595" alt="Screenshot 2023-11-22 at 3 06 51 PM" src="https://github.com/stakwork/sphinx-swarm/assets/32662508/335c4772-0219-462f-afa0-872fd9f72521">

### Acceptance Criteria

- [ ] I have tested this on Chrome
- [ ] I have posted a screen recording that displays all the following states above including the error response of an invalid email address

**Comment by Evanfeenstra** [comment]
This should be a pop-up that forces the user to choose a new username and password. The username is REQUIRED to be a valid email, so they can always "recover password" if they forget it. Frontend should validate the email format

**Comment by Evanfeenstra** [comment]
Here's the backend route: https://github.com/stakwork/sphinx-swarm/blob/master/src/routes.rs#L187

**Comment by VividhPandey003** [comment]
hey, What is the tech stack required for this?

**Comment by ecurrencyhodler** [comment]
I believe coding languages are rust and typescript. Frontend should be mostly typescript.

**Comment by ecurrencyhodler** [comment]
Okay we are closing this issue for now.
