### ISSUE TITLE
Add versions for each part of the stack

### ISSUE THREAD

**Issue by tomsmith8** [stakwork/sphinx-swarm#150]
**Task**

It would be great to understand which version Jarvis, boltwall, navfiber etc. is on in the UI:

<img width="1916" alt="image" src="https://github.com/stakwork/sphinx-swarm/assets/142233216/74da2914-2e4b-4224-aeac-88edbd6c6847">

**Comment by Evanfeenstra** [comment]
Docker versions are super frustrating… the hash u get locally doesnt match the hash on dockerhub

the easiest way would be to expose a version in the code itself (like an endpoint). What do you think @tomsmith8

**Comment by tomsmith8** [comment]
Interesting! Ok yeah, that could work. I'll create a ticket on Jarvis and Boltwall.
