### ISSUE TITLE
Manually update admin token on swarms

### ISSUE THREAD

**Issue by tomsmith8** [stakwork/sphinx-swarm#164]
**Task**

Manually add admin tokens for each swarm:

- [x] swarm5
- [x] swarm12
- [ ] swarm13
- [x] swarm21
- [x] swarm22
- [x] swarm23
- [x] swarm25
- [x] swarm26
- [x] swarm27

**Comment by tobi-bams** [comment]
Having an Issue updating Swarm12, below is the Error Message

remote: Enumerating objects: 263, done.
remote: Counting objects: 100% (263/263), done.
remote: Compressing objects: 100% (88/88), done.
fatal: write error: No space left on device
fatal: fetch-pack: invalid index-pack output

@kevkevinpal and @Evanfeenstra

**Comment by tobi-bams** [comment]
Swarm 13 is not accessible, I always see this error: Operation timed out

**Comment by kevkevinpal** [comment]
Not near my PC rn but try `docker system prune`

**Comment by tobi-bams** [comment]
> Not near my PC rn but try `docker system prune`

Thanks @kevkevinpal I was able to update Swarm12 after running `docker system prune`

Please do you have the IP for Swarm27 also I am not able to connect to Swarm13, it keeps timing out
