### ISSUE TITLE
Bitcoind interface

### ISSUE THREAD

**Issue by Evanfeenstra** [stakwork/sphinx-swarm#17]
in the backend, find a way to call the bitcoind instance and get info using this lib https://github.com/rust-bitcoin/rust-bitcoincore-rpc

The first task is the just do the "getinfo" call, and print out the block number

@elraphty

**Comment by kevkevinpal** [comment]
@elraphty for now if you want to just print out the getinfo call as a json blob in the panel that would be a good first step

we can make it look better from there forward

**Comment by Evanfeenstra** [comment]
actually @elraphty can you make the "block mining" UX in the sidebar itself? Not in a modal. Too many modal is bad UX.

We can have a little number box called "Number of Blocks", and then the "Mine" button next to it. They should ONLY show if the network is "regtest"
