### ISSUE TITLE
Update UI in Swarm for Secondbrain

### ISSUE THREAD

**Issue by tomsmith8** [stakwork/sphinx-swarm#190]
**Task**

Improve the UX and UI for secondbrain admin functionality.

**Current**

![Image](https://github.com/stakwork/sphinx-nav-fiber/assets/142233216/a523a196-1f28-4bba-99c7-2f016ffd5f4b)

**Rough sketch:**

- Keen to explore different ideas though
![Image](https://github.com/stakwork/sphinx-nav-fiber/assets/142233216/9c98d8f5-0f6a-4f9c-8e4b-fc0882bec8f4)

![Image](https://github.com/stakwork/sphinx-nav-fiber/assets/142233216/918467c2-a373-4c62-810c-c3af9217ba24)

**Functionality:**

- Toggle secondbrain to be public private
- Add/Set Superadmin
  - Manage/change superadmin 
- Add/Set Roles Subadmin and Member
- View roles
- Delete User
- Toggle endpoints free/paid
- Open Secondbrain from this view
- Success/Failure
- Table => Name | Pubkey | Role

**Comment by tomsmith8** [comment]
Full Screen:


![Image](https://github.com/stakwork/sphinx-swarm/assets/142233216/cedca2ef-6cff-4491-8e10-e0b8d04964f2)

Success / Failure:


![Image](https://github.com/stakwork/sphinx-swarm/assets/142233216/1202ed84-deb3-442c-8ee6-30446bfd91c5)

First interaction - must set superadmin to view table, to add other subadmins/members:



![Image](https://github.com/stakwork/sphinx-swarm/assets/142233216/6e71f225-d0eb-498e-817a-00f7c3239ea1)

Delete:

![Image](https://github.com/stakwork/sphinx-swarm/assets/142233216/1f5e4bc7-a5b7-45e6-9502-b3a861b1213a)

**Comment by tomsmith8** [comment]
Notifications updating routes:


![Image](https://github.com/stakwork/sphinx-swarm/assets/142233216/38d8ec74-5b5e-4195-b076-d619715f0ac3)

**Comment by tomsmith8** [comment]
@Antanasijevic Functionality in 'General' to set `Title`

**Comment by Antanasijevic** [comment]
https://github.com/stakwork/sphinx-swarm/assets/13258550/91661d1d-cbcc-492e-bb2c-677bccf33ba9

**Comment by tomsmith8** [comment]
Cool - Do you have the link to the Figma File for Swarm?

**Comment by tomsmith8** [comment]
We'll have to make this public and lock it down (for bounty hunters)

**Comment by Antanasijevic** [comment]
> We'll have to make this public and lock it down (for bounty hunters)

@tomsmith8 Ok, let me just clean it up, and it will be ready.

**Comment by Antanasijevic** [comment]
Final Figma Layouts 
https://www.figma.com/file/Bm9JpMST4u9BFeiZdggmZX/Swarm?type=design&node-id=1409%3A937&mode=design&t=Kxj5DeNDshGAaTqE-1

https://github.com/stakwork/sphinx-swarm/assets/13258550/14189a60-8e6b-44bf-a5f0-c5d4d5bbbb2d

**Comment by tomsmith8** [comment]
Looks awesome! I'll add a few comments to Figma
