### ISSUE TITLE
Open Secondbrain button is broken with dynamic addresses

### ISSUE THREAD

**Issue by tomsmith8** [stakwork/sphinx-swarm#192]
**Task**

If we set a dynamic address e.g `machinelearning.sphinx.chat` open second brain button links to old domain.

We should extract from boltwall env.

<img width="335" alt="image" src="https://github.com/stakwork/sphinx-swarm/assets/142233216/dd0c0e81-330b-4084-901a-6b5996de21ce">

**Acceptance Criteria**

- [ ] Button works when dynamic subdomain not set = nav.swarm29.sphinx.chat
- [ ] Button works when dynamic subdomain is set = machinelearning.sphinx.chat

**Comment by Evanfeenstra** [comment]
i went ahead and fixed this, sry didn't see it was assigned already

https://github.com/stakwork/sphinx-swarm/commit/e97e11bc3bcf568906d206d2901d26a0eaf34540

**Comment by tomsmith8** [comment]
No problem, thanks @Evanfeenstra !
