### ISSUE TITLE
Tribes stats

### ISSUE THREAD

**Issue by Evanfeenstra** [stakwork/sphinx-swarm#23]
"stats" sidebar for tribes. The `tribes` image in the stack has a `url` parameter. You can use that to pull the real data from the tribes server. You can pull all tribes from `/tribes` to show:
 - how many tribes
list tribes. sort tribes by:
 - my tribes (owner_pubkey matches a user from relay)
 - most popular (user count)
 - most recent messages
 - has a "preview" page on sphinx-cache. Click to open preview page.
 
You can pull all people from `/people`
- list people profiles -> link to their profile page

**Comment by elraphty** [comment]
@Evanfeenstra I have listed the tribes, is there a way to get tribe users, or do I just have to list all the users from the /people endpoint?

**Comment by Evanfeenstra** [comment]
@elraphty the top of the tribes stats should have two tabs (like the relay sidebar), with "tribes" and "people"

There is no way to get tribe users
