### ISSUE TITLE
Swarm - Save and delete

### ISSUE THREAD

**Issue by tomsmith8** [stakwork/sphinx-swarm#232]
![Image](https://github.com/stakwork/sphinx-swarm/assets/142233216/526b4935-b827-4c0e-b5c5-cf9c49da2000)

**Comment by Antanasijevic** [comment]
@tomsmith8 Here are layouts for editing user.

Before Change
https://www.figma.com/design/Bm9JpMST4u9BFeiZdggmZX/Swarm?node-id=1795-2190&t=zxA2vuq5xjT2bocO-1

After Change
https://www.figma.com/design/Bm9JpMST4u9BFeiZdggmZX/Swarm?node-id=1795-2270&t=zxA2vuq5xjT2bocO-1

**Comment by tomsmith8** [comment]
Thanks @Antanasijevic 

cc @tobi-bams
