### ISSUE TITLE
Add ability to set price

### ISSUE THREAD

**Issue by tomsmith8** [stakwork/sphinx-swarm#240]
**Task**

Default value = 10sats

Admin can decide to change the price of the endpoint:

- Add input item to the screen below
- Grey out if toggled off?
- Toggled on, user should be able to update the cost
![Image](https://github.com/stakwork/sphinx-swarm/assets/142233216/1504d861-1419-4725-89c0-e0bc6f688b07)

**Comment by Antanasijevic** [comment]
@tomsmith8 You can find final layout here
https://www.figma.com/design/Bm9JpMST4u9BFeiZdggmZX/Swarm?node-id=1433-4339&t=3NS1TEUHj5F8vrvD-1
