### ISSUE TITLE
LND channel manager

### ISSUE THREAD

**Issue by Evanfeenstra** [stakwork/sphinx-swarm#26]
![Channel Manager](https://user-images.githubusercontent.com/13258550/205131706-9f7884ac-e869-41d0-ac1a-5133c45ee051.png)

**Comment by Evanfeenstra** [comment]
@elraphty did you say you already started this frontend?

**Comment by elraphty** [comment]
Yes, it's on the lndmanager branch.

**Comment by Evanfeenstra** [comment]
@elraphty please take a look at my changes to the `lndrpc` file. I was able to add automatic `Serialize` trait to the tonic structs by forking the `tonic_lnd` library here https://github.com/Evanfeenstra/tonic_lnd/blob/add-serde/build.rs

So you dont need to make copy structs just to add `Serialize`. Feel free to push to that repository if you need to add `Serialize` to more structs
