### ISSUE TITLE
[APOC issue] it was not downloaded

### ISSUE THREAD

**Issue by tomsmith8** [stakwork/sphinx-swarm#306]
**Description:**

We need to create a Dockerfile that builds a custom Neo4j image with APOC procedures included. This custom image should be based on an existing Neo4j image, and all dependencies, including APOC, should be pre-installed within the image.

**Requirements:**

Base image: Neo4j (official image from Docker Hub).
Include APOC library (latest stable version).
Ensure that all necessary configurations for APOC and any other plugins are done within the Dockerfile.
The final image should be a standalone build that can be run as a Docker container with APOC enabled out of the box.

**Acceptance Criteria:**

- [ ] A fully functioning Dockerfile that can be built and deployed.
- [ ] The resulting Docker image should run Neo4j with APOC installed and available.
- [ ] The image should be capable of being used in any environment with standard Neo4j configurations.

**Comment by tomsmith8** [comment]
@omoniyi24 is this something you can do?

**Comment by omoniyi24** [comment]
Yes, I'm on this already. I've moved the APOC download into the Dockerfile as requested. However, I'm currently facing an issue with the mounted volume when the container runs, the host path's content is overriding the container's content, causing the downloaded JAR files to disappear. I'm looking into a solution to ensure the APOC files persist as expected.
