### ISSUE TITLE
Manually installing SSM Agent on Debian Server instances

### ISSUE THREAD

**Issue by tomsmith8** [stakwork/sphinx-swarm#308]
Link: https://docs.aws.amazon.com/systems-manager/latest/userguide/agent-install-deb.html

**Task**

Add agent that allows us to manage the servers without the need to login via SSH, so if we can add this to be part of the pipeline 
 (it’s AWS specific).

**Comment by tobi-bams** [comment]
@tomsmith8 This is done, Gonza installed this for some of the machines already.

I guess I will have to find a way to do this automatically when we create swarms from super admin.
