### ISSUE TITLE
Update Swarm Action buttons

### ISSUE THREAD

**Issue by tomsmith8** [stakwork/sphinx-swarm#321]
**Task**

Move buttons inside side panel:

- Stop/Start
- Restart
- Logs
- Update

![Image](https://github.com/user-attachments/assets/03a7999a-54bd-4183-a0f6-c78124230fac)

**Comment by Antanasijevic** [comment]
@tomsmith8 Here are some updates we discussed:

Default version with just Logs and additional menu

https://www.figma.com/proto/Bm9JpMST4u9BFeiZdggmZX/Swarm?node-id=1871-17033&node-type=canvas&t=Ndg5ovNYcQh3T1yr-1&scaling=min-zoom&content-scaling=fixed&page-id=1552%3A10774&starting-point-node-id=1871%3A17033&show-proto-sidebar=1


In case update is available, do you think we can show green button here, indicating this option?

https://www.figma.com/proto/Bm9JpMST4u9BFeiZdggmZX/Swarm?node-id=1872-11362&node-type=canvas&t=Ndg5ovNYcQh3T1yr-1&scaling=min-zoom&content-scaling=fixed&page-id=1552%3A10774&starting-point-node-id=1872%3A11362&show-proto-sidebar=1


Similar to Update, once user press "Start" in dropdown, a red "Stop" button may show up here

https://www.figma.com/proto/Bm9JpMST4u9BFeiZdggmZX/Swarm?node-id=1872-11723&node-type=canvas&t=Ndg5ovNYcQh3T1yr-1&scaling=min-zoom&content-scaling=fixed&page-id=1552%3A10774&starting-point-node-id=1872%3A11723&show-proto-sidebar=1

**Comment by Antanasijevic** [comment]
@tomsmith8 All layouts are updated with new buttons.
Updated Header and drop down buttons can be found here
https://www.figma.com/design/Bm9JpMST4u9BFeiZdggmZX/Swarm?node-id=1516-8073&t=OFCsVjEeZTOS1Bax-1

Layout Preview
![image](https://github.com/user-attachments/assets/59a4da00-b21c-49fc-b775-7ab085b2fe2f)

**Comment by tomsmith8** [comment]
Can you share an exact example but swapping 'Start' with 'Stop' when the state is the other way around
