### ISSUE TITLE
Deployment bugs on EC2

### ISSUE THREAD

**Issue by Evanfeenstra** [stakwork/sphinx-swarm#33]
When running sphinx-swarm on EC2, there are issues related to filesystem permissions. Something about the Docker API needs to be fixed (only on linux. Works fine on Mac)

I don't think its related to SELinux, because I turned off the SE features and the bug persists.

For example `sphinx-proxy` throws  `Cannot write pid file "/badger/LOCK": open /badger/LOCK: permission denied`

`sphinx-relay` throws a `Error::ThrowAsJavaScriptException napi_throw` error relayed to SQLITE

Figure out what needs to change in the Config struct passed into `start_container` to fix the permissions issue on linux

bitcoind:
```
************************
EXCEPTION: NSt10filesystem7__cxx1116filesystem_errorE       
filesystem error: cannot create directories: Permission denied [/data/.bitcoin/regtest/wallets]       
bitcoin in AppInit()
```

**Comment by jairunet** [comment]
Hello Evan,

Have you reviewed the following possible causes:

Which user is running/creating the file? and check if that user has sufficient permissions to create or write to the file.
$ ls -l filename

`-rw-r--r-- 12 linuxize users 12.0K Apr  8 20:51 filename.txt
|[-][-][-]-   [------] [---]
| |  |  | |      |       |
| |  |  | |      |       +-----------> 7. Group
| |  |  | |      +-------------------> 6. Owner
| |  |  | +--------------------------> 5. Alternate Access Method
| |  |  +----------------------------> 4. Others Permissions
| |  +-------------------------------> 3. Group Permissions
| +----------------------------------> 2. Owner Permissions
+------------------------------------> 1. File Type
`
https://linuxize.com/post/chmod-command-in-linux/

Another detail to check is the location specified for the PID file, ensure that the location exists and that it is writable.

Also, make verify if there is already a file with the same name in the specified location, you can test by removing the file and trying to execute the program.

And lastly,  please check that the docker container has the appropriate space left.

Hope this help,

**Comment by Evanfeenstra** [comment]
thanks for the tips @jairunet! i do think it is user-related. The docker API does not have very good documentation, but I figured out that the `user` field in image creation accept the UID only (in docker-compose the format is `GID:UID` so i was confused). I think I am on the right track now...

**Comment by Evanfeenstra** [comment]
Even running the containers as `root`, and also providing `0` as the docker `user` UID, throws the same errors. I checked in the volumes, every directory is owned by `root`... yet I'm still getting `permission denied`... argggg

**Comment by jairunet** [comment]
I wonder if this might be of help:

First, make sure your $USER variable is set
$ echo $USER

Then
$ sudo usermod -aG docker $USER

Next, log out of the system

When you log in again, restart the docker service with:
$ sudo systemctl restart docker

Then
$ docker ps

Then try again.

**Comment by jairunet** [comment]
Might be a good idea to review the way docker and docker-compose were installed originally, here is the long list of checks I do while working with docker and docker-compose:

INSTALLING DOCKER IN UBUNTU 20.04 LTS
• $ curl -fsSL https://get.docker.com/ -o [get-docker.sh](http://get-docker.sh/) < best steps to install docker in Linux.
• then sudo bash <docker script>

INSTALLING DOCKER-COMPOSE IN UBUNTU 20.04 LTS
• https://docs.docker.com/compose/cli-command/#install-on-linux < best installation steps for docker-compose in Linux.
• DOCKER_CONFIG=${DOCKER_CONFIG:-$HOME/.docker}
• mkdir -p $DOCKER_CONFIG/cli-plugins
• curl -SL https://github.com/docker/compose/releases/download/v2.6.1/docker-compose-linux-x86_64 -o $DOCKER_CONFIG/cli-plugins/docker-compose
• chmod +x $DOCKER_CONFIG/cli-plugins/docker-compose
• sudo cp $DOCKER_CONFIG/cli-plugins/docker-compose /usr/local/bin
• sudo usermod -aG docker $USER

**Comment by Evanfeenstra** [comment]
The fix included
- make sure images didn't create things as `root`
- use docker-managed containers (named containers) instead of bind mounts
