### ISSUE TITLE
Shutdown old LND node used for l402s/LSATs

### ISSUE THREAD

**Issue by tomsmith8** [stakwork/sphinx-swarm#359]
**Task**

Instance `(second brain node) 050.sphinxnodes.chat`

We need to shutdown an old LND node that is currently used for L402s across all swarms.

We should point this at either:

- Swarm4 (this is easiest but requires migrating to v2 in the future anyway)
- V2 node we control (unsure on requirements if this will work)

**Comment by kevkevinpal** [comment]
I'm going to try and get the second brain swarms connected to swarm 4 since I know it is an LND node and we use if for bounties so the liquidity will be fine 

Then we should be able to shutdown cluster 50

**Comment by kevkevinpal** [comment]
It shouldn't matter if its a v2 relay or not since we just need LND for it to work

**Comment by Evanfeenstra** [comment]
Ya LMK if you want the info to point to the v2 payout bot. But swarm4 LND should work fine as well

**Comment by kevkevinpal** [comment]
This issue should be good to close, they are all pointing at swarm4 now
