### ISSUE TITLE
Internal Health Check via IP

### ISSUE THREAD

**Issue by tomsmith8** [stakwork/sphinx-swarm#390]
**Task**

For Swarm, we need an internal health check that can be accessed directly by IP address. We’re setting up a load balancer, and it requires a health check that works via IP rather than a domain or API path (e.g. it can't use /api/about). 

**Acceptance Criteria**

- [ ] Set up an IP-accessible health check that will allow the load balancer to verify service status

**Comment by Evanfeenstra** [comment]
@tomsmith8 can this have port? We are using LetsEncrypt, so we need to keep port 80 reserved for certificate auto-renewal

**Comment by Evanfeenstra** [comment]
also... why do we need a load balancer for each swarm? its a waste of $ IMO, since traefik is working as a reverse proxy

**Comment by tomsmith8** [comment]
Assigning to @tobi-bams

**Comment by Evanfeenstra** [comment]
GET /health returning `{"status":"ok"}` should be fine
