### ISSUE TITLE
Auto-restart `payment bot` on cron job

### ISSUE THREAD

**Issue by tomsmith8** [stakwork/sphinx-swarm#421]
cron_job = daily

We need to restarted the payment bot for LSPs

**Comment by Evanfeenstra** [comment]
First lets start with auto-restart container on a cron job

So in the main config there can be a `auto_restart` optional array with names of containers

And a `auto_restart_time` (Like 2 = UTC 2am) to restart each container listed

Make sense?

**Comment by tobi-bams** [comment]
> First lets start with auto-restart container on a cron job
> 
> So in the main config there can be a `auto_restart` optional array with names of containers
> 
> And a `auto_restart_time` (Like 2 = UTC 2am) to restart each container listed
>
> Make sense?

Yea, it does make sense.
