### ISSUE TITLE
Swarm inteface

### ISSUE THREAD

**Issue by Antanasijevic** [stakwork/sphinx-swarm#5]
use second brain layout
with only 6-7 boxes

Box/icon similar to second brain for the following: - LND node - Tribe server - Relay - Proxy server - Meme server - Line = lightning channel - Line = MQTT connection

3 variations of a server icons
variety of colors
Colored Box with icon and name

**Comment by Antanasijevic** [comment]
![image](https://user-images.githubusercontent.com/13258550/199712921-06c85e18-953b-4bf4-a9aa-f820221a477b.png)

**Comment by Evanfeenstra** [comment]
@Antanasijevic can you attach the raw icons here?

**Comment by Antanasijevic** [comment]
Here are PNG icons
You can also grab additional icons, and other properties in this figma project
https://www.figma.com/file/Bm9JpMST4u9BFeiZdggmZX/Swarm?node-id=508%3A1114


![lightning_channel](https://user-images.githubusercontent.com/13258550/199853010-ec3ebef2-d845-4da1-b6a3-7e62fdf34d90.png)
![lnd](https://user-images.githubusercontent.com/13258550/199853013-d2566af2-8df1-46fc-9a4c-123598a0a94d.png)
![meme](https://user-images.githubusercontent.com/13258550/199853016-72ea5626-0083-4879-8d62-6ed9c3b3da0b.png)
![MQTT](https://user-images.githubusercontent.com/13258550/199853017-c2b7d352-b207-434a-be7a-704a6ed7d80b.png)
![proxy](https://user-images.githubusercontent.com/13258550/199853019-10238124-19a5-4c7e-9efb-de25338e431a.png)
![relay](https://user-images.githubusercontent.com/13258550/199853023-df1bf058-70a8-43db-bd76-f582c307dbf4.png)
![tribe](https://user-images.githubusercontent.com/13258550/199853024-e84a3d72-b707-4f8c-819a-c3ae189b4891.png)

**Comment by Evanfeenstra** [comment]
@Antanasijevic I think we should have some metadata on each box too. Like a name, a logo, and another area for extra metadata (like how many users are signed up etc). Check out Polar, it has a similar UX to what we are building. https://lightningpolar.com/

**Comment by Antanasijevic** [comment]
@Evanfeenstra @kevkevinpal Ok, seems like we need to go back to start, but this time we must do it properly.
Unfortunately, we had several improvisations like this, and it made huge waste of design time.
In order for a designer to make any kind of interface, a detailed specification is needed.
Proper specification must be made before any design work is done.
Without clear specification, it can not be done or delegated properly, and even if some work can be done, usually it turns out to be unusable, because instructions were not clear.

Having an example like one you sent is very useful, but it is still just an example. 
What i need in order to proceed with this or delegate it, is a detailed description of what you need with all elements.
Also for all the data, i need samples of all the content that will be featured on these screens.

For next step, i need developers involved in this project to make clear and detailed specification, with examples. 
If Paul approves that, i will proceed with work, or delegate it.

@Evanfeenstra Can you please organize a specification for us so we can proceed? Thank you

**Comment by pitoi** [comment]
@Antanasijevic 
this is a quick prototype to test how the functionality works.

**Comment by Evanfeenstra** [comment]
@Antanasijevic 

Ok... requirements are evolving on this, but here is what we know we need:

1. Flowchart like you made above, but with a little more metadata on each box. Remember this is an interface for getting work done. Definitely check out the Polar UI, i think it looks and feels very professional. Each box should have:
    - service name
    - service logo
    - some metadata (like `42 connected clients` for relay, for example).
    
2. When you click on a box, it opens a sidebar with form fields for that box (depending on the type).

3. The `Relay` sidebar will be the most complex, so maybe you could design that one.
    - List current users 
    - Click on a user and see their name, pubkey, route hint, and invite QR code
    - Add new user
    
4. A top-level button for adding a new node (like a new LND instance) to the graph. It will also need to connect with others, so this might be a form where there is a dropdown to select other nodes to connect to.

**Comment by Antanasijevic** [comment]
@Evanfeenstra  Thanks Evan, this specification helps a lot, I will now be able to produce pretty detailed first version.
Let me put together a mockup with all elements included, and we can continue from there. 
If that is ok, I may reach out to you in the process of making first version, to consult you about details.

**Comment by Antanasijevic** [comment]
@Evanfeenstra I have assembled a rough version based on current description. You can check out Figma prototype here
https://www.figma.com/proto/Bm9JpMST4u9BFeiZdggmZX/Swarm?node-id=728%3A365&scaling=contain&page-id=508%3A1114&starting-point-node-id=728%3A365

Or check the video preview below.
Please let me know when is a good time for a call so we can review it together. Thanks.

https://user-images.githubusercontent.com/13258550/201120318-9c13b940-60da-4de2-a7a4-be04e00f8877.mp4

**Comment by Evanfeenstra** [comment]
looks amazing @Antanasijevic ! Can we get the PNG logos with their correct colors? or SVGs so we can alter the colors?

**Comment by Antanasijevic** [comment]
@Evanfeenstra Sure, maybe it is best to go with SVG and switch color in code. I will send you files shortly. Please let me know if you want to connect so we can review it together.

**Comment by Antanasijevic** [comment]
@Evanfeenstra Here is a link with SVG icons. Beside ones used in mockup, there are few additional icons, in case they are needed.

**Comment by Antanasijevic** [comment]
@Evanfeenstra Wow, that was fast. Looks great. Please let me know if we can catch up on a call, i may need few additional details.

**Comment by kevkevinpal** [comment]
Just adding this link as it has a lot of elements that we'd want for the LND portion
https://raw.githubusercontent.com/lightninglabs/lightning-terminal/master/app/src/assets/images/screenshot.png

**Comment by Antanasijevic** [comment]
@Evanfeenstra @kevkevinpal Do you something like this may work?
![image](https://user-images.githubusercontent.com/13258550/205131706-9f7884ac-e869-41d0-ac1a-5133c45ee051.png)
