### ISSUE TITLE
relay default tribes

### ISSUE THREAD

**Issue by Evanfeenstra** [stakwork/sphinx-swarm#59]
FRONTEND ONLY FOR NOW

In the `Configuration` section of the `Relay` sidebar.
- dont use `<Controls />`
- instead make a separate RelayControls component
- `Default Tribes` section
- "Selected tribes will be auto-joined by new users on this relay"
- dropdown with tribes owned by the admin of relay (use fake data for now)
- when you select a tribe, it is added to a list above the dropdown
- each added tribe also has an "X" next to it, that you can click to remove the tribe

I will work on the backend for this... but i need to figure out a few things in proxy and relay first. For now this is a frontend only task

**Comment by elraphty** [comment]
@Evanfeenstra  This is the UI I designed for the default tribes ![Design image](img[https://i.ibb.co/fQ6fxLz/Screenshot-2023-01-20-at-19-05-38.png)
