### ISSUE TITLE
new connection QRs

### ISSUE THREAD

**Issue by Evanfeenstra** [stakwork/sphinx-swarm#80]
2 new QR codes to connect to your node:

1. `connect::{HOST}::{PUBKEY}`
    - then you can call the `/contacts/tokens` route to make your auth token for a new proxy user

2. `claim::{HOST}::{BASE64_ENCODED_TOKEN}`
    - then you can call PUT contacts/:id to update your alias and contact_key etc. 

HOST will be like `relay.swarm.sphinx.chat`, so you can use that to call relay

@tomastiminskas

**Comment by Evanfeenstra** [comment]
@jimBeaux27

**Comment by tomastiminskas** [comment]
Opening this again since it needs to be done on the other clients as well (android/Mac/kotlin-cross-platform)

**Comment by tomastiminskas** [comment]
@Evanfeenstra the only issue right now is that the apps can't connect to socket when signed up to swarm server
