### ISSUE TITLE
Start, stop, and update node bugfixes

### ISSUE THREAD

**Issue by elraphty** [stakwork/sphinx-swarm#98]
-  Proxy continues to restart after upgrading it
-  Bitcoin can't process requests after restarting it
-  LND can't process requests after restarting it
-  Server freezes after restarting an LND node
-  Clicking on an external node throws a state error which makes the app stall

**Comment by Evanfeenstra** [comment]
@elraphty please focus on frontend issues for now. 

For me, LND can process requests just fine after restarting. So can all the other ones. Are you running from latest master?

**Comment by elraphty** [comment]
> @elraphty please focus on frontend issues for now.
> 
> For me, LND can process requests just fine after restarting. So can all the other ones. Are you running from latest master?

After I pulled, it from master I realized LND works fine, but if Bitcoin is restarted, or upgraded it does not load the wallet, which might lead to some issues for LND
